### ISSUE TITLE
Hide default options

### ISSUE THREAD

**Issue by valorin** [HiroKws/ArtisanBashCompletion#1]
This is absolutely fantastic. Good work :-)

Is it possible to disable the default Symfony Console options from autocomplete?

For example, consider this:

```
> artisan make:request -<tab><tab>
--ansi            --help            --no-interaction  -v                --version         
--env=            -n                -q                -V                -vv               
-h                --no-ansi         --quiet           --verbose         -vvv    
```

It looks like we have a lot of options, but all of them are the boring Symfony defaults that you usually ignore, so in reality, there are no options for this command.

Then look at this:

```
> artisan make:command -<tab><tab>
--ansi            --handler         --no-ansi         --queued          -V                -vv               
--env=            --help            --no-interaction  --quiet           --verbose         -vvv              
-h                -n                -q                -v                --version
```

Hidden in there are the command specific options... but it's hard to easily visually process them because they are mixed with the defaults which we don't care about.

**Comment by HiroKws** [comment]
Hi,

As default, they must be displayed. Because they are useful as "reminder".

And it is defference what option bother them. So it must be optional !

I had added new feature to erase displaying specfied options. Check new version.

**Comment by valorin** [comment]
Great, thanks :-)
